[package]
name = "Relclis"
version = "0.0.1"
edition = "2021"
license = " AGPL-3.0-or-later"
description = "NOT READY YET! A simple, non bloated boilerplate for doing CLI's. Rust easy lightweight command line interface system."
authors = ["KirovClassBattleCruiser"]

[dependencies]
# Relclis